### PR TITLE
Added a function to calculate the point value of a move to the Session class

### PR DESCRIPTION
**Pull request by William-Cook**
Pushing to prevent future merge conflicts. Also did some stuff to user and subclasses but don't worry about that for now

### CODE REVIEW

**Comment by William-Cook** [comment]
Session is referenced in user classes to allow access to all the things it needs

**Comment by William-Cook** [comment]
Yeah you're right I forgot about that, I'll fix it. There will still be a new method in Session though.

**Comment by William-Cook** [comment]
Good catch

**Comment by richardjamesw** [comment]
👍

**Pull request closed without merging**
