### PR TITLE
API Servlet

### PR DESCRIPTION
**Pull request by andrewld3**

### CODE REVIEW

**Comment by andrewld3** [comment]
I believe changes are made. Can you check if target is being ignored?

**Comment by landonp1203** [comment]
@andrewld3 They are not being ignored, do this:

```
git rm -r --cached .
git add .
git commit -m "fixed untracked files"
```

Taken from: https://stackoverflow.com/questions/11451535/gitignore-is-not-working

**Comment by William-Cook** [comment]
So many hoops geezzzz... Glad you're handling this Andrew, thank you

**Comment by William-Cook** [comment]
@landonp1203 is this something we'll have to do every time, or is it a one time thing

**Comment by landonp1203** [comment]
@William-Cook No you will not have to do this every time. One time thing.

**Comment by William-Cook** [comment]
Gotcha thanks buddy

**Comment by andrewld3** [comment]
Alright, .gitignore should be working. I have it pushed up to branch

**Pull request merged**
